name: Android Build Test

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "backup-branch12344" ]
  pull_request:
    branches: [ "backup-branch12344" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@main
      
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.4 #v1.1.4 is the latest version as of now or you can use master for the latest commit
        with:
          haxe-version: 4.3.6
      
      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
      
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk