name: Android Build Test

on:
  workflow_dispatch:

jobs:
  Android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.2
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true 

      - name: Compile APK (Debug mode, no keystore)
        run: |
          haxelib run lime build android -debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/debug/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
